### ISSUE TITLE
Can you provide a ue demo？

### ISSUE THREAD

**Issue by stanle1** [DKingAlpha/JsonLiveLinkExample#1] opened 2023-09-15 07:36 UTC
Can you provide a ue demo？

**Comment by DKingAlpha** [comment] 2023-09-15 07:50
Following the README should lead you a running skeleton.

**Comment by stanle1** [comment] 2023-09-15 07:57
对ue了解不深，py这部分也能通，jsonlink这部分绿点也能亮

**Comment by DKingAlpha** [comment] 2023-09-15 08:40
> 对ue了解不深，py这部分也能通，jsonlink这部分绿点也能亮

See Section `Usage` Step `3`

**Comment by stanle1** [comment] 2023-09-15 08:59
无效。估计是ue工程配置的问题
![image](https://github.com/DKingAlpha/JsonLiveLinkExample/assets/12638025/4fd34849-9f90-4a1f-9635-56664edea7ba)

**Comment by DKingAlpha** [comment] 2023-09-15 09:03
Did you follow Usage:Step1? You should edit definition of variable `skeleton` before use.

Update skeleton to match the actual bones, then you should be able to drag the bones in matplot to see reflections in UE.

EDIT: See `Bones Definition` in README

EDIT 2:
```
skeleton = {
"root": {
      "pelvis": ...
    }
}
```

**Comment by DKingAlpha** [comment] 2023-09-15 09:07
To clarify, as implied by the repo name, this repo is a demonstration of Json Live Link protocol. This script should not be used in real production. Instead it helps you understand the protocol and develop your own animation streaming workflow

**Comment by stanle1** [comment] 2023-09-15 09:17
![image](https://github.com/DKingAlpha/JsonLiveLinkExample/assets/12638025/6d19565c-1ae0-4f12-975a-98ecc9f5af98)
??

**Comment by DKingAlpha** [comment] 2023-09-15 09:21
Bad definition of middle_01_l. It has parent middle_metacarpal_l which is not in the definition thus Parent=-1

**Comment by DKingAlpha** [comment] 2023-09-15 09:21
Maybe start with simpler skeleton.

**Comment by stanle1** [comment] 2023-09-15 09:36
still no work

**Comment by stanle1** [comment] 2023-09-15 09:40
![image](https://github.com/DKingAlpha/JsonLiveLinkExample/assets/12638025/8cd67abe-ce34-4b14-a5da-a10acfc3fad9)

**Comment by DKingAlpha** [comment] 2023-09-15 09:44
You should set ParentID of all defined bones except root, not just -1. That's why my `skeleton` variable exists. It's laterly flattened to linear array with correct ParentID.

**Comment by stanle1** [comment] 2023-09-15 09:45
![image](https://github.com/DKingAlpha/JsonLiveLinkExample/assets/12638025/afdf6fe5-4d47-4849-b577-29da6ebdf521)

**Comment by stanle1** [comment] 2023-09-15 09:57
Provide a simple ue demo?

**Comment by DKingAlpha** [comment] 2023-09-15 10:15
https://github.com/DKingAlpha/JsonLiveLinkExample/assets/15340687/c205bd6d-5542-4f05-9d2b-886bfbf180ed

The problem is in your code, not UE project. A demo will not help you solve this, the original script might. You should definitely test with the original code before integrating it to your peoject.
The steps to create a demo have been described in README.

**Comment by stanle1** [comment] 2023-09-15 10:27
The reason for the problem is the issue with the ue code, but I am a beginner in ue and would like to refer to a simple blueprint and corresponding binding

**Comment by DKingAlpha** [comment] 2023-09-15 10:30
no UE code or BP is needed to get it working. SKMesh preview should be enough.

**Comment by stanle1** [comment] 2023-09-15 10:32
Provide a SKMesh file for testing？

**Comment by DKingAlpha** [comment] 2023-09-15 10:50
You will find a lot in UE installation folder.

**Comment by DKingAlpha** [comment] 2023-09-15 11:17
Re-created a new project and confirmed that humanoid skeleton mesh is working with Json LiveLink.
Closing this issue.

**Closed as completed by DKingAlpha** 2023-09-15 11:17 UTC

**Comment by stanle1** [comment] 2023-09-18 08:47
Simple ue project： not work  https://image-touchtv.oss-cn-shenzhen.aliyuncs.com/ipa/sdk/bbb.zip

![image](https://github.com/DKingAlpha/JsonLiveLinkExample/assets/12638025/1632ecee-855a-45ea-a56a-da47f1a2fdcd)

still not work

**Comment by stanle1** [comment] 2023-09-18 09:19
The reason is that different versions are used JSONLiveLink.

https://github.com/justdark/UE_Android_LiveLink/tree/main/JSONLiveLink

![image](https://github.com/DKingAlpha/JsonLiveLinkExample/assets/12638025/4000ed2a-858f-46f2-ac37-245174fb3449)

**Comment by DKingAlpha** [comment] 2023-09-18 09:54
That repo has stated that JsonLiveLink is modified.

What about the official JsonLiveLink? Did you get it working?

**Comment by stanle1** [comment] 2023-09-18 10:09
official JsonLiveLink is to old
